name: Deploy MkDocs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-deploy.yml'
  workflow_dispatch: # Permite disparar o deploy manualmente

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o plugin git-revision-date-localized ler o histórico do git

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Deploy para o GitHub Pages
        run: mkdocs gh-deploy --force
